cevi/automatic_walk-time_tables

- python_program/automatic_walk_time_tables/find_swisstopo_name.py
- python_program/automatic_walk_time_tables/find_walk_table_points.py
- python_program/automatic_walk_time_tables/log_helper.py
- python_program/automatic_walk_time_tables/map_downloader/create_map.py
- python_program/automatic_walk_time_tables/map_numbers.py
- python_program/automatic_walk_time_tables/walk_table.py
- python_program/main.py
This PR adds logging statements instead of print(...).
This PR will close #22.
> Add Logging

- webinterface/package.json
> Bump Version number

- python_program/automatic_walk_time_tables/utils/file_parser.py
- webinterface/package.json
> fix #64: Failing GPX file in v2.2.0 

- python_program/automatic_walk_time_tables/geo_processing/find_walk_table_points.py
- python_program/automatic_walk_time_tables/walk_time_table/walk_table.py
- webinterface/package.json
Changing the data structure resulted in data being in kilometres inst…ead of metres. This PR fixes this, by converting back to km while writing the excel file
> Fix kilometer bug

- swiss_TLM_api/app.py
- swiss_TLM_api/swiss_TML_api/map_numbers/map_numbers_fetcher.py
- swiss_TLM_api/swiss_TML_api/name_finding/name_finder.py
> Fix index building - closes #118

- .github/workflows/cypress.yml
- .github/workflows/dev_build.yml
- .github/workflows/prod_build.yml
> add caching to action

- .env.ci-testing
- .env.local-dev
- .env.prod-dev
- .env.prod-latest
- backend/app.py
> add redirect to frontend if download is not found

- frontend/src/app/app.module.ts
- frontend/src/app/pages/export-settings/export-settings.component.html
- frontend/src/app/pages/export-settings/export-settings.component.scss
- frontend/src/app/pages/export-settings/export-settings.component.ts
- frontend/src/app/services/map-animator.service.ts
- addresses #141
- addresses #145
> improved error handling for route uploading

- backend/app.py
- frontend/src/app/pages/download-data/download-data.component.html
- frontend/src/app/pages/download-data/download-data.component.ts
This should be merged into dev after #168
addresses #82 and #158
> Add a download button #82 and #158

- backend/app.py
- docs/changelog/changelog.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/app/pages/download-data/download-data.component.html
- frontend/src/app/pages/download-data/download-data.component.ts
* add a download buttom #82 and #158
* Bump webpack and @angular-devkit/build-angular in /frontend
* update change log
> Version 3.1.0 (#171)

- Readme.md
Improve readme by adding development notes in german as well.
> Improve readme

- .env.ci-testing
- .env.local-dev
- .env.prod-dev
- .env.prod-latest
- backend/Dockerfile
- backend/local-dev.Dockerfile
- docker-compose.ci-testing.yml
- e2e/package.json
Add some ENV variables from within the docker files into the right .env files.
> Fix Issue 138 & Cypress ENV

- e2e/Dockerfile
Hopefully this makes the CI work again...
> Update Cypress Docker Container to newer version

- backend/app.py
- backend/automatic_walk_time_tables/path_transformers/heigth_fetcher_transfomer.py
- e2e/Dockerfile
- swiss_TLM_api/local-dev.Dockerfile
GET -> POST
The URL gets too long for routes with many points, and the request fails. Putting the geom into the body prevents this.
I needed to add the apt install to start the Docker Compose on an M1 Mac (MacOS 14). I'm not sure why that is required only for MacOS.
> fix: post to api3.geo.admin instead of get

- .github/workflows/create_release.yml
- backend/app.py
- backend/automatic_walk_time_tables/path_transformers/heigth_fetcher_transfomer.py
- backend/requirements.txt
- docs/package-lock.json
- docs/package.json
- e2e/Dockerfile
- e2e/package-lock.json
- e2e/package.json
- frontend/package-lock.json
- frontend/package.json
- swiss_TLM_api/requirements.txt
- Update Dependencies
- Fix GET/POST Bug, thanks @johannschwabe !
> Version 4.0.2 - Update dependencies & Bug Fix

- backend/automatic_walk_time_tables/path_transformers/douglas_peucker_transformer.py
- backend/automatic_walk_time_tables/path_transformers/pois_transfomer.py
- docs/changelog/changelog.md
- frontend/package.json
- frontend/src/app/components/upload-area/upload-area.component.html
- frontend/src/app/services/map-animator.service.ts
- frontend/src/app/services/map.service.ts
- implements #147 
- Added waypoints are now more likely to be selected for the Excel export
> Add option to delete waypoints

- .github/workflows/dev_build.yml
- .github/workflows/prod_build.yml
- backend/app.py
- backend/automatic_walk_time_tables/generator.py
- frontend/package.json
- swiss_TLM_api/swiss_TML_api/map_numbers/map_numbers_fetcher.py
This PR fixes the bug described in #453 and changes the backend such that the user settings is taken into account again.
Thanks @carlobeltrame for pointing out the bug.
> Fix bug #453

- backend/app.py
- backend/automatic_walk_time_tables/generator.py
- backend/automatic_walk_time_tables/walk_time_table/walk_table.py
- backend/requirements.txt
- docker-compose.local-dev.yml
- docker-compose.prod-dev.yml
- docker-compose.prod-latest.yml
- docs/changelog/changelog.md
- e2e/cypress/e2e/utils.js
- frontend/package.json
- frontend/src/app/pages/export-settings/export-settings.component.html
- frontend/src/app/pages/export-settings/export-settings.component.ts
- route_engine/helper_scripts/converter.py
Content of this PR:
- remove of height profile
- cleanup of AutomatedWalkTableGenerator class
- always generate excel and pdf
With this PR, the height profile support is dropped.
the user can no longer select whether to generate excel or pdf, both are generated.
> [5.1.0] Remove Height profile

- route_engine/Dockerfile
- route_engine/README.md
- route_engine/dev.Dockerfile
- route_engine/entrypoint.sh
This PR fixes #499.
However, I had to switch back to the latest tag, as apparently there is no version staged with 3.5.0. This needs further investigation...
> Upgrade Valhalla Version

- frontend/src/app/helpers/swisstopo-map.ts
This PR changes the map center to be the same as swiss topo map.geo.admin.ch
> Change map center to be swiss center and zoom like map.geo.admin.ch
